// <auto-generated />
using System;
using CampusEventos.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusEventos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("CampusEventos.Api.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TB_CATEGORIAS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Descricao = "Oficinas práticas e capacitações técnicas",
                            Nome = "Workshop"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Descricao = "Apresentações com especialistas do mercado",
                            Nome = "Palestra"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Descricao = "Maratonas de desenvolvimento e inovação",
                            Nome = "Hackathon"
                        });
                });

            modelBuilder.Entity("CampusEventos.Api.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("TB_EVENTOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacidadeMaxima = 40,
                            CategoriaId = 1,
                            DataHora = new DateTime(2026, 10, 15, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Workshop focado em novidades do C# e boas práticas com EF Core",
                            Local = "Laboratório 504 - Campus Paulista",
                            Preco = 0.00m,
                            Titulo = "Imersão em C# e .NET 10"
                        },
                        new
                        {
                            Id = 2,
                            CapacidadeMaxima = 150,
                            CategoriaId = 2,
                            DataHora = new DateTime(2026, 10, 20, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Palestra sobre o impacto da IA no desenvolvimento corporativo",
                            Local = "Auditório FIAP",
                            Preco = 0.00m,
                            Titulo = "Inteligência Artificial Generativa no Mercado"
                        });
                });

            modelBuilder.Entity("CampusEventos.Api.Models.Evento", b =>
                {
                    b.HasOne("CampusEventos.Api.Models.Categoria", "Categoria")
                        .WithMany("Eventos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CampusEventos.Api.Models.Categoria", b =>
                {
                    b.Navigation("Eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
